sudo: false
language: node_js
node_js:
  - "5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - develop
    - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - bower install
  - gulp build
script:
  - npm test
  - gulp test:fend
after_success:
  - npm run report-coverage
  - gulp merger-coverage-report
  - npm run coveralls
deploy:
  provider: heroku
  api_key: 8dbc5730-c35c-4c11-9022-e67974b0c1f3
  app:
    develop: dockip-staging
    master: dockip
after_deploy:
  - gulp heroku
